# first stage
FROM python:3.9 AS builder
WORKDIR /code

COPY requirements.txt .

# install dependencies to the local user directory (eg. /root/.local)
RUN pip install --user -r requirements.txt

# second unnamed stage
FROM python:3.9-slim AS runner
WORKDIR /code

# copy only the dependencies installation from the 1st stage image
COPY --from=builder /root/.local /root/.local

# copy the content of the local src directory to the working directory
COPY Main/ ./Main/
COPY app.py .

# Make the database
RUN python -m flask db init
RUN python -m flask db migrate -m ""
RUN python -m flask db upgrade

# update PATH environment variable
ENV PATH=/root/.local:$PATH

EXPOSE 5000

# command to run on container start
CMD [ "python", "./app.py" ]